import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(__dirname, '..');
const require = createRequire(import.meta.url);

const outputDir = path.join(workspaceRoot, 'packages/lib/shader/generated/slang_materials');
const tempDir = path.join(workspaceRoot, '.tmp/slang-pbr-materials');
const generatedGlslPath = path.join(tempDir, 'slang-pbr.include.glsl');
const generatedMetadataPath = path.join(tempDir, 'slang-pbr.codegen.json');
const glslPath = path.join(outputDir, 'material_kernel.glsl');
const metadataPath = path.join(outputDir, 'material_kernel.codegen.json');
const energyCompensation = process.env.SLANG_PBR_ENERGY_COMPENSATION ?? 'analytic';

function getLocalPackageRoot() {
  const candidates = [
    process.env.SLANG_PBR_ROOT,
    path.resolve(workspaceRoot, '../slang-pbr'),
    path.resolve(workspaceRoot, '../gltf-pt/vendor/slang-pbr'),
  ].filter(Boolean);

  for (const candidate of candidates) {
    const packageJsonPath = path.join(candidate, 'package.json');
    if (existsSync(packageJsonPath)) return candidate;
  }
  return null;
}

function resolvePackagePath(specifier, localPackageRoot) {
  if (localPackageRoot) {
    if (specifier === 'slang-pbr/package.json') return path.join(localPackageRoot, 'package.json');
    if (specifier === 'slang-pbr/tools/generate') return path.join(localPackageRoot, 'tools/generate.mjs');
    if (specifier === 'slang-pbr/enterprise_pbr.slang') return path.join(localPackageRoot, 'src/enterprise_pbr.slang');
    if (specifier === 'slang-pbr/manifest') return path.join(localPackageRoot, 'src/api.manifest.json');
  }

  try {
    return require.resolve(specifier);
  } catch (error) {
    throw new Error(
      `Could not resolve ${specifier}. Run yarn install after adding the slang-pbr dependency, ` +
      `or set SLANG_PBR_ROOT to a local slang-pbr checkout.`,
      { cause: error },
    );
  }
}

function runGenerator(generatorPath) {
  const result = spawnSync(process.execPath, [
    generatorPath,
    '--target', 'glsl',
    '--kind', 'include',
    '--out-dir', tempDir,
    '--energy-compensation', energyCompensation,
  ], {
    cwd: workspaceRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  if (result.status !== 0) {
    process.stderr.write(result.stderr || result.stdout || '');
    process.exit(result.status || 1);
  }
  if (result.stdout) process.stdout.write(result.stdout);
}

function prepareWebGlInclude(glsl) {
  return glsl
    .replace(/^#version\s+\d+\s*\n/gm, '')
    .replace(/^#extension\s+[^\n]+\n/gm, '')
    .replace(/^layout\(row_major\)\s+uniform;\n/gm, '')
    .replace(/^layout\(row_major\)\s+buffer;\n/gm, '')
    .replace(/^#line[^\n]*\n/gm, '')
    .replace(/^\s*\[\[(?:unroll|loop|flatten|branch)\]\]\s*\n/gm, '')
    .trim();
}

async function main() {
  await mkdir(outputDir, { recursive: true });
  await rm(tempDir, { recursive: true, force: true });
  await mkdir(tempDir, { recursive: true });

  const localPackageRoot = getLocalPackageRoot();
  const generatorPath = resolvePackagePath('slang-pbr/tools/generate', localPackageRoot);
  const packageJsonPath = resolvePackagePath('slang-pbr/package.json', localPackageRoot);
  const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));
  const entryPath = resolvePackagePath('slang-pbr/enterprise_pbr.slang', localPackageRoot);
  const manifestPath = resolvePackagePath('slang-pbr/manifest', localPackageRoot);

  runGenerator(generatorPath);

  const generatedGlsl = prepareWebGlInclude(await readFile(generatedGlslPath, 'utf8'));
  const generatedMetadata = JSON.parse(await readFile(generatedMetadataPath, 'utf8'));
  const sanitizedGeneratedMetadata = {
    ...generatedMetadata,
    targets: {
      glsl: {
        ...(generatedMetadata.targets?.glsl ?? {}),
        path: 'packages/lib/shader/generated/slang_materials/material_kernel.glsl',
      },
    },
  };

  const glsl = `// AUTO-GENERATED by tools/generate_slang_materials.mjs
// Include-safe GLSL library emitted by slang-pbr.
// Do not edit by hand.

${generatedGlsl.trim()}
`;
  await writeFile(glslPath, glsl, 'utf8');

  const metadata = {
    version: 2,
    package: {
      name: packageJson.name,
      version: packageJson.version,
      entry: 'slang-pbr/enterprise_pbr.slang',
      manifest: 'slang-pbr/manifest',
    },
    generator: {
      command: 'slang-pbr-generate',
      module: 'slang-pbr/tools/generate',
      target: 'glsl',
      kind: 'include',
      energyCompensation,
    },
    slangPbr: sanitizedGeneratedMetadata,
    targets: {
      glsl: {
        available: true,
        path: 'packages/lib/shader/generated/slang_materials/material_kernel.glsl',
      },
    },
  };
  await writeFile(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`, 'utf8');
  await rm(tempDir, { recursive: true, force: true });

  console.log(`Wrote ${path.relative(workspaceRoot, glslPath)}`);
  console.log(`Wrote ${path.relative(workspaceRoot, metadataPath)}`);
}

await main();
